version: "3.8"
services:
  gpt-load:
    image: gpt-load:latest # 使用本地构建的镜像
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    container_name: gpt-load
    ports:
      - ${PORT:-3001}:${PORT:-3001}
    environment:
      - PORT=3001
      - HOST=0.0.0.0
      - SERVER_READ_TIMEOUT=60
      - SERVER_WRITE_TIMEOUT=600
      - SERVER_IDLE_TIMEOUT=120
      - SERVER_GRACEFUL_SHUTDOWN_TIMEOUT=10
      - IS_SLAVE=false
      - TZ=Asia/Shanghai
      - AUTH_KEY=1968121800
      - MAX_CONCURRENT_REQUESTS=100
      - ENABLE_CORS=true
      - ALLOWED_ORIGINS=*
      - ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - ALLOWED_HEADERS=*
      - ALLOW_CREDENTIALS=false
      - LOG_LEVEL=info
      - LOG_FORMAT=text
      - LOG_ENABLE_FILE=true
      - LOG_FILE_PATH=/app/data/logs/app.log
      - DATABASE_DSN=/app/data/gpt-load.db
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
    volumes:
      - /Users/ofeiss/docker/gpt-load/data:/app/data
    stop_grace_period: ${SERVER_GRACEFUL_SHUTDOWN_TIMEOUT:-10}s
    healthcheck:
      test: wget -q --spider -T 10 -O /dev/null http://localhost:${PORT:-3001}/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dockge_default
networks:
  dockge_default:
    external: true
